### ISSUE TITLE
Curious if we could use npm name?

### ISSUE THREAD

**Issue by robertleeplummerjr** [computes/gpu#1]
I didn't see any project supported here, and was curious if there wasn't a plan, could we use the npm name for: https://github.com/gpujs/gpu.js?

**Comment by computes** [comment]
We will be adding GPU support to Computes.io soon using the following library - https://github.com/MaiaVictor/WebMonkeys

**Comment by robertleeplummerjr** [comment]
Did you see the question on if we could use the gpu name on npm?  Would that at all be possible?

**Comment by computes** [comment]
I thought that I answered you. We have plans for the gpu npm name.

**Comment by robertleeplummerjr** [comment]
ty
